// bus 事件名常量：格式 域.动作；payload 契约见 docs/engineering-context/05-conventions.md §1 与 03-business-logic.md 事件契约
export const EV = {
  // 战斗
  COMBAT_HIT: 'combat.hit',
  COMBAT_KILL: 'combat.kill',
  COMBAT_BACKSTAB: 'combat.backstab',
  COMBAT_PERFECTBLOCK: 'combat.perfectblock',
  COMBAT_DODGE: 'combat.dodge',
  COMBAT_CAVALRYKILL: 'combat.cavalrykill',
  COMBAT_COUNTER: 'combat.counter',
  COMBAT_ULTIMATE: 'combat.ultimate',
  // 连击
  COMBO_TIER: 'combo.tier',
  COMBO_BREAK: 'combo.break',
  COMBO_FINISHER: 'combo.finisher',
  // 技能
  SKILL_CAST: 'skill.cast',
  SKILL_REJECT: 'skill.reject',
  // 战役
  CAMPAIGN_CLEAR: 'campaign.clear',
  CAMPAIGN_PERFECT: 'campaign.perfect',
  // 每日
  DAILY_UPDATE: 'daily.update',
  DAILY_COMPLETED: 'daily.completed',
  // 成就
  ACHIEVEMENT_UNLOCK: 'achievement.unlock',
  // 词条
  AFFIX_DROP: 'affix.drop',
  // Boss
  BOSS_SUMMON: 'boss.summon',
  // 特效
  FX_SHAKE: 'fx.shake',
  FX_PERFECTBLOCK: 'fx.perfectBlock',
  FX_PERFECTDODGE: 'fx.perfectDodge',
  // UI
  UI_LOCKLOST: 'ui.locklost',
  UI_LOCKED: 'ui.locked',
  HUD_FLASH: 'hud.flash',
  HUD_MISS: 'hud.miss',
  HUD_BOSSPHASE: 'hud.bossPhase',
  // 皮肤
  SKINS_CHANGED: 'skins.changed',
  // 设置
  SETTINGS_QUALITY: 'settings.quality',
  SETTINGS_SENSITIVITY: 'settings.sensitivity',
  SETTINGS_DIFFICULTY: 'settings.difficulty',
  // 回合
  ROUND_RESTART: 'round.restart',
  // 状态机
  STATE_CHANGE: 'state.change',
  // 引擎
  ENGINE_ERROR: 'engine.error',
  // 小地图
  MINIMAP_SUPPLY: 'minimap.supply',
  // AI
  AI_CALLREINFORCE: 'ai.callReinforce',
  AI_SPOTPLAYER: 'ai.spotPlayer'
};
